server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  swagger:
    enabled: true
    title: spring-boot-demo
    description: Swagger API
    version: 1.0.0-SNAPSHOT
    contact:
      name: Picongzhi
      email: picongzhi@gmail.com
      url: http://picongzhi.com
    #    swagger扫描的基础包，默认：全扫描
    #    base-package:
    #    需要处理的基础URL规则，默认：/**
    #    base-path:
    #    需要排除的URL规则，默认：空
    #    exclude-path:
    security:
      # 是否启用swagger登录认证
      filter-plugin: false
      username: picongzhi
      password: 123456
    global-response-messages:
      GET[0]:
        code: 400
        message: Bad Request
      GET[1]:
        code: 404
        message: NOT FOUND
      GET[2]:
        code: 500
        message: ERROR
      POST[0]:
        code: 400
        message: Bad Request
      POST[1]:
        code: 404
        message: NOT FOUND
      POST[2]:
        code: 500
        message: ERROR