server:
  port: 8080
  servlet:
    context-path: /demo
qiniu:
  # 七牛云 access key
  accessKey: test
  # 七牛云 secret key
  secretKey: test
  # 七牛云 bucket
  bucket: test
  # 七牛云 域名
  prefix: test
spring:
  servlet:
    multipart:
      enabled: true
      location: /Users/picongzhi/workspace/java/idea/spring-boot-demo/upload/tmp
      file-size-threshold: 5MB
      max-file-size: 20MB